// ◊·κ=1 · Annex IV documentation generator · pure functions · zero deps

export const DOC_FIELDS = [
  { id: 'system_name', q: 'System name & version', placeholder: 'e.g. FallVet CV Scorer v2.3', art: 'Annex IV(1)(a)' },
  { id: 'provider', q: 'Provider name + address + contact', placeholder: 'Your company · registered address · contact email', art: 'Annex IV(1)(a)' },
  { id: 'purpose', q: 'Intended purpose (specific use case)', placeholder: 'Scoring software-engineer CVs against role specifications', art: 'Annex IV(1)(b)' },
  { id: 'users', q: 'Intended users + deployment context', placeholder: 'In-house recruiters at Acme GmbH · German labour market', art: 'Annex IV(1)(c)' },
  { id: 'architecture', q: 'System architecture · models · components', placeholder: 'TF-IDF + logistic regression · BERT embeddings · scoring rubric', art: 'Annex IV(2)(a)' },
  { id: 'training_data', q: 'Training data origin · curation · annotation', placeholder: '5000 anonymised CVs + role pairings · 3 senior recruiters', art: 'Annex IV(2)(d)' },
  { id: 'data_governance', q: 'Data governance · bias examination', placeholder: 'Group-fairness metrics (TPR · FPR) measured per protected attribute', art: 'Article 10' },
  { id: 'risk_mgmt', q: 'Risk management system', placeholder: 'Risk: bias against career gaps → mitigation: feature exclusion + review', art: 'Article 9' },
  { id: 'accuracy', q: 'Accuracy metrics + test datasets + results', placeholder: 'F1 = 0.83 on held-out test (n=500) · ROC-AUC = 0.91', art: 'Article 15' },
  { id: 'human_oversight', q: 'Human oversight measures', placeholder: 'Threshold gate · stop button · audit log of overrides', art: 'Article 14' },
  { id: 'cybersecurity', q: 'Cybersecurity measures', placeholder: 'Input sanitisation · adversarial testing · client-side execution', art: 'Article 15' },
  { id: 'logging', q: 'Logging design', placeholder: 'Inference log + SHA-256 prevHash chain · 12-month IndexedDB retention', art: 'Article 12' },
  { id: 'instructions', q: 'Instructions for deployers', placeholder: 'User guide · limitations · threshold tuning · escalation paths', art: 'Article 13' },
  { id: 'post_market', q: 'Post-market monitoring + serious incident reporting', placeholder: 'Weekly dashboard · 24h triage SLA · authority contact list', art: 'Articles 72-73' },
];

/**
 * Generate an Annex IV technical documentation Markdown file from field values.
 *
 * @param {object} values - object keyed by field id (see DOC_FIELDS) with string values
 * @param {{ date?: string, draftWarning?: boolean }} opts
 * @returns {string} markdown document
 */
export function generateAnnexIV(values, opts = {}) {
  values = values || {};
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const draftWarning = opts.draftWarning !== false;
  const v = id => values[id] || '_[fill in]_';

  let md = `# Technical Documentation · EU AI Act Annex IV\n\n`;
  md += `> Generated: ${date} · per Regulation (EU) 2024/1689\n\n`;
  if (draftWarning) {
    md += `> ⚠ This is a starting draft. Review with qualified counsel before use as official conformity documentation.\n\n`;
  }
  md += `---\n\n## 1 · General description\n\n`;
  md += `**System name & version:** ${v('system_name')}\n\n`;
  md += `**Provider:** ${v('provider')}\n\n`;
  md += `**Intended purpose:** ${v('purpose')}\n\n`;
  md += `**Intended users + deployment context:** ${v('users')}\n\n`;
  md += `---\n\n## 2 · Description of system elements\n\n`;
  md += `### 2.1 Architecture & components\n\n${v('architecture')}\n\n`;
  md += `### 2.2 Training data (Article 10)\n\n${v('training_data')}\n\n`;
  md += `### 2.3 Data governance & bias examination\n\n${v('data_governance')}\n\n`;
  md += `### 2.4 Risk management system (Article 9)\n\n${v('risk_mgmt')}\n\n`;
  md += `### 2.5 Accuracy, robustness & cybersecurity (Article 15)\n\n**Accuracy:** ${v('accuracy')}\n\n`;
  md += `**Cybersecurity:** ${v('cybersecurity')}\n\n`;
  md += `### 2.6 Human oversight (Article 14)\n\n${v('human_oversight')}\n\n`;
  md += `### 2.7 Logging (Article 12)\n\n${v('logging')}\n\n`;
  md += `---\n\n## 3 · Instructions for deployers (Article 13)\n\n${v('instructions')}\n\n`;
  md += `---\n\n## 4 · Post-market monitoring & incident reporting (Articles 72-73)\n\n${v('post_market')}\n\n`;
  md += `---\n\n## 5 · EU Declaration of Conformity (Article 47)\n\n`;
  md += `_To be signed by the provider once all other sections are complete and verified by qualified counsel._\n\n`;
  md += `- Name & address of provider: _[fill in]_\n`;
  md += `- AI system identification: ${v('system_name')}\n`;
  md += `- Declaration of conformity with Regulation (EU) 2024/1689\n`;
  md += `- Harmonised standards applied: _[list if applicable]_\n`;
  md += `- Date · Place · Signature\n\n`;
  md += `---\n\n_Generated by fall-euaiact SDK · MIT · github.com/sjgant80-hub/fall-euaiact_\n`;
  return md;
}

/**
 * Get the list of field definitions for building a UI form
 * @returns {Array<{ id: string, q: string, placeholder: string, art: string }>}
 */
export function getDocFields() {
  return DOC_FIELDS.slice();
}

/**
 * Validate a values object · returns missing field ids
 * @param {object} values
 * @returns {string[]} array of missing field ids
 */
export function validateValues(values) {
  return DOC_FIELDS.filter(f => !values?.[f.id] || !values[f.id].trim()).map(f => f.id);
}
